# 开发环境配置

[app]
environment = "development"
log_level = "debug"

[server]
host = "127.0.0.1"
port = 3000

[jwt]
# 开发环境使用较长的过期时间以便于调试
access_token_expiry = 60
refresh_token_expiry = 1
refresh_token_remember_me_expiry = 3

[database]
# 开发环境使用独立的数据库文件
url = "hwsystem_dev.db"

[cache]
type = "moka"
