# 开发环境配置

[app]
environment = "development"
log_level = "debug"

[server]
host = "127.0.0.1"
port = 3000

[jwt]
# 开发环境使用较长的过期时间以便于调试
access_token_expiry = 60
refresh_token_expiry = 1
refresh_token_remember_me_expiry = 3

[database]
type = "postgresql"
host = "192.168.1.9"
port = 54321
name = "hwsystem_dev"
user = "hwsystem"
password = "Aa123456"
pool_size = 5
timeout = 30

[cache]
type = "moka"
